INSERT INTO wp_posts (post_title, post_content, post_name, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, post_status, post_type) VALUES ('Forth Estate: New Editions', '
<h2 class=\"showTitle\"><em>Forth Estate: New Editions</em></h2>', 'Forth_Estate_New_Editions', '2018-05-06 15:31:46', '2018-05-06 15:31:46', '2018-05-06 15:31:46', '2018-05-06 15:31:46', 1, 'publish','galleryarchive');
INSERT INTO wp_posts (post_title, post_content, post_name, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, post_status, post_type) VALUES ('Caitlin Teal Price', '
<h2 class=\"showTitle\"><em>Caitlin Teal Price</em></h2>
<p>Presented by Capricious</p>
<p>March 15 - May 5</p>
<p>Opening reception for the artist: Tuesday, March 15, 6-8pm</p>
<p>Gallery Hours:<br/>
Friday &amp; Sunday 1-6pm <br/>
By Appointment<br/>
<br/>
Please email <a href=\"mailto:info@thewildproject.com\" target=\"_blank\">info@thewildproject.com</a></p>
<p><a href=\"http://www.becapricious.com\" target=\"_blank\">www.becapricious.com</a></p>
<p><a href=\"http://www.caitlintealprice.com\" target=\"_blank\">www.caitlintealprice.com</a></p>
<p><img alt=\"Caitlin Teal Price\" border=\"0\" src=\"http://localhost:3000/wp-content/themes/wildproject/images/gallery/2011-Caitlin-Teal-Price.jpg\"/></p>
<p>In <em>Annabelle, Annabelle</em> women stand transfixed in severe everyday landscapes, connected to the world by the objects surrounding them. Each frame is carefully constructed but what lies just beyond is uncertain, perhaps threatening and ultimately left for wonder. These women, with strength and wisdom in the depth of their age, stand boldly and carefully alone, and offer us the opportunity to create stories about life and death, power and vulnerability, magnificence and uncertainty.</p>
<p><em>Caitlin Teal Price</em> was born in 1980 in Chicago, IL, and grew up in Washington, DC. She received her BFA in photography from the Parsons School of Design in 2002, and her MFA from the Yale School of Art in 2009. In 2010, she was awarded the Kodak film grant from Too Much Chocolate and an honorable mention from the New York Photo Awards. She has exhibited her work nation wide and is in the collection of the Robert V. Fullerton Art Museum in San Bernardino, CA. Her work has been published in The New Yorker, Vice, The Believer, Nylon, Details, Vogue, Famous and Capricious magazines. This is the first showing of her most recent project Annabelle, Annabelle and her first solo show in New York City. Caitlin currently lives and works in Washington, DC.</p>
<p><em>Capricious Presents</em> is a roving curatorial project and an extension of the former Capricious Space. It is also the newest offshoot of Capricious Magazine and Publishing. Founded by artist Sophie Mörner in 2004, Capricious is dedicated to showcasing emerging fine art photography. Its contributors and subject matter span the globe. And while constant change is a primary Capricious trait, there are definite common visual threads running throughout its history. Capricious has an affinity for things like animals, androgyny, opposition, reclaimed life, lust, natural as well as urban life, intimacy, revolution and nostalgia. Hanna Liden, Ryan McGinley, Esther Teichmann, Nick Haymes, Olaf Breuning, Melanie Bonajo and Skye Parrott are just a few of the dozens of
photographers whose early work has been promoted by Capricious. As a group of projects and publications, Capricious occupies a rare and whimsical space between commercial and fashion photography; it operates as both a tool for discovering new talent and as an artists\' oasis.</p>', 'Caitlin_Teal_Price', '2018-05-06 15:31:46', '2018-05-06 15:31:46', '2018-05-06 15:31:46', '2018-05-06 15:31:46', 1, 'publish','galleryarchive');
INSERT INTO wp_posts (post_title, post_content, post_name, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, post_status, post_type) VALUES ('Maureen Drennan
Meet Me in the Green Glen', '
<h2 class=\"showTitle\"><em>Maureen Drennan<br/>
<br/>Meet Me in the Green Glen</em></h2>
<p>October 12 - December 18th, 2011</p>
<p>Opening reception for the artist:<br/>
Wednesday, October 12, 6-8pm</p>
<p><img alt=\"\" border=\"0\" src=\"http://localhost:3000/wp-content/themes/wildproject/images/gallery/2011-Maureen-Drennan.jpg\"/></p>
<h2 class=\"firstheader\">The artist states:</h2>
<p>\"This is body of work is a portrait of Ben, a marijuana grower in California. Although marijuana is legal to grow and use in California within strict guidelines, there are situations in which it is still illegal. It is not culturally acceptable to grow or sell despite the fact that it is a large part of the local economy. Every year Ben hires young men to help with the harvest season. They work for about one month and then he is alone again. The story I am communicating is not simply about pot growing, it is also about the experience of a socially isolated person and our relationship.</p>
<p>American Literature, in particular Flannery O’Connor and Annie Proulx, have had a significant influence on my work. They depict flawed characters and anti-heroes for whom life is a constant struggle, yet have grace. In describing the landscape both writers evoke an ominously psychological and emotional sense of place in which the environment becomes a character unto itself and amplifies the aloneness of the characters.\"</p>', 'Maureen_DrennanMeet_Me_in_the_Green_Glen', '2018-05-06 15:31:47', '2018-05-06 15:31:47', '2018-05-06 15:31:47', '2018-05-06 15:31:47', 1, 'publish','galleryarchive');
INSERT INTO wp_posts (post_title, post_content, post_name, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, post_status, post_type) VALUES ('Aperture Foundation’s Limited-Edition Contemporary Prints Exhibition', '
<h2 class=\"showTitle\"><em>Aperture Foundation’s Limited-Edition Contemporary Prints Exhibition</em></h2>
<p>May 11–September 7, 2011</p>
<p>Opening Reception: Wednesday, June 29, 6-8pm</p>
<p>Artists in the exhibition include: Michel Campeau, Maureen Drennan, Doug DuBois, JH Engström, Todd Hido, Kalle Kataila, Mark Lyon, Edgar Martins, and Bas Princen. </p>
<p><img alt=\"\" border=\"0\" src=\"http://localhost:3000/wp-content/themes/wildproject/images/gallery/2011-Aperture-1.jpg\"/></p>
<p>The Wild Project is pleased to present an exhibition of limited-edition prints produced by Aperture Foundation. Aperture Foundation is a leading photography non-profit dedicated to promoting photography in all its forms based in Chelsea. The exhibition focuses on contemporary artists whose work, in many cases, has been featured in Aperture Magazine, Aperture books, in exhibitions at Aperture Gallery or have been winners of the Portfolio Prize contest.</p>
<p>Aperture Foundation is proud to have one of the longest running limited-edition print and portfolio programs in the United States. The print program started in the 1960’s with collaborations between the master photographers Paul Strand and later with Edward Steichen. The print program expanded over the years to offer richly diverse editions and portfolios to art lovers and collectors. Today the program works with several artists’ estates and presents prints that range from masters of the medium, to established contemporary artists and finally highlights many emerging artists of tomorrow. Proceeds from the sales benefit the artists and helps maintain the quality of Aperture’s publications and public programming. The print program supports the organization’s non-profit mission to advance photography in all its forms.</p>', 'Aperture_Foundations_LimitedEdition_Contemporary_Prints_Exhibition', '2018-05-06 15:31:47', '2018-05-06 15:31:47', '2018-05-06 15:31:47', '2018-05-06 15:31:47', 1, 'publish','galleryarchive');
